- hosts: jenkins
  become: true

  tasks:
        - name: Update apt cache
          apt: update_cache=yes

        - name: Installing necessary packets 
          apt: name={{ item }} update_cache=yes state=present
          with_items:
           - software-properties-common
           - python-pip
           - virtualbox
           - git
           - python-dev

        - name: Installing vagrant
          apt:
            deb: https://releases.hashicorp.com/vagrant/1.9.5/vagrant_1.9.5_x86_64.deb

        - name: Installing ansible
          pip:
            name: ansible
            state: latest
